service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: us-east-2

functions:
  orders:
    handler: dist/main.handler
    events:
      - httpApi:
          path: /
          method: GET
